// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvzdpbkalibgilmltukz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2emRwYmthbGliZ2lsbWx0dWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzkwOTcsImV4cCI6MjA2NzAxNTA5N30.lmHPkZHCsQ5I1iyRS6tiwFXIX2qw3GxkOh01pB6YRho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});