// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtfxkohzlyypazrnzxhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0Znhrb2h6bHl5cGF6cm56eGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDMzMTEsImV4cCI6MjA2NzExOTMxMX0.16kT_jfVqytzTVpg_Phj_o80S8z2GTGPWe_a33u0sOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});